/* Sample user/employee */
INSERT INTO PUBLIC.STORE_USER (ID,CREATEDATE,CREATEUSER,ISACTIVE,UPDATEDATE,UPDATEUSER,COMMENTS,EMAIL,FIRSTNAME,GENDER,LASTNAME,PASSWORD,"ROLE",USERNAME) VALUES (
1,'2017-04-20 00:00:00.000',NULL,true,NULL,NULL,NULL,'jim@rentacasum.com','Jim','MALE','Beam','employee1','USER','employee1');

/* Sample Customers */
INSERT INTO PUBLIC.CUSTOMER (ID,CREATEDATE,CREATEUSER,ISACTIVE,UPDATEDATE,UPDATEUSER,BIRTHDAY,COMMENTS,EMAIL,FIRSTNAME,GENDER,LASTNAME,ORGANIZATION,PASSWORD,PROMOTIONCODE,USERNAME) VALUES (
1,'2017-04-20 00:00:00.000',NULL,true,NULL,NULL,NULL,NULL,'john@smith.com','John','MALE','Smith',NULL,NULL,NULL,NULL);
INSERT INTO PUBLIC.CUSTOMER (ID,CREATEDATE,CREATEUSER,ISACTIVE,UPDATEDATE,UPDATEUSER,BIRTHDAY,COMMENTS,EMAIL,FIRSTNAME,GENDER,LASTNAME,ORGANIZATION,PASSWORD,PROMOTIONCODE,USERNAME) VALUES (
2,'2017-04-20 00:00:00.000',NULL,true,NULL,NULL,NULL,NULL,'jack@doe.com','Jack','MALE','Doe',NULL,NULL,NULL,NULL);
INSERT INTO PUBLIC.CUSTOMER (ID,CREATEDATE,CREATEUSER,ISACTIVE,UPDATEDATE,UPDATEUSER,BIRTHDAY,COMMENTS,EMAIL,FIRSTNAME,GENDER,LASTNAME,ORGANIZATION,PASSWORD,PROMOTIONCODE,USERNAME) VALUES (
3,'2017-04-20 00:00:00.000',NULL,true,NULL,NULL,NULL,NULL,'liz@banks.com','Liz','FEMALE','Banks',NULL,NULL,NULL,NULL);
INSERT INTO PUBLIC.CUSTOMER (ID,CREATEDATE,CREATEUSER,ISACTIVE,UPDATEDATE,UPDATEUSER,BIRTHDAY,COMMENTS,EMAIL,FIRSTNAME,GENDER,LASTNAME,ORGANIZATION,PASSWORD,PROMOTIONCODE,USERNAME) VALUES (
4,'2017-04-20 00:00:00.000',NULL,true,NULL,NULL,NULL,NULL,'jenny@houston.com','Jenny','FEMALE','Houston',NULL,NULL,NULL,NULL);

/* Sample Movies */
INSERT INTO PUBLIC.MOVIE (ID,CREATEDATE,CREATEUSER,ISACTIVE,UPDATEDATE,UPDATEUSER,DESCRIPTION,IMDBCODE,RELEASEDATE,TITLE,"TYPE") 
    VALUES (1,'2017-01-01 00:00:00.000',NULL,true,NULL,NULL,'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.','tt0111161','1994-01-01 00:00:00.000','The Shawnshank Redemption','OLD');
    INSERT INTO PUBLIC.MOVIE (ID,CREATEDATE,CREATEUSER,ISACTIVE,UPDATEDATE,UPDATEUSER,DESCRIPTION,IMDBCODE,RELEASEDATE,TITLE,"TYPE") 
    VALUES (2,'2017-01-01 00:00:00.000',NULL,true,NULL,NULL,' The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.','tt0068646','1994-01-01 00:00:00.000','The Godfather','OLD');
    INSERT INTO PUBLIC.MOVIE (ID,CREATEDATE,CREATEUSER,ISACTIVE,UPDATEDATE,UPDATEUSER,DESCRIPTION,IMDBCODE,RELEASEDATE,TITLE,"TYPE") 
    VALUES (3,'2017-01-01 00:00:00.000',NULL,true,NULL,NULL,'In the near future, a weary Logan cares for an ailing Professor X somewhere on the Mexican border.','tt3315342','2017-01-01 00:00:00.000','Logan','NEW_RELEASE');
    INSERT INTO PUBLIC.MOVIE (ID,CREATEDATE,CREATEUSER,ISACTIVE,UPDATEDATE,UPDATEUSER,DESCRIPTION,IMDBCODE,RELEASEDATE,TITLE,"TYPE") 
    VALUES (4,'2017-01-01 00:00:00.000',NULL,true,NULL,NULL,'A jazz pianist falls for an aspiring actress in Los Angeles.','tt3783958','2017-01-01 00:00:00.000','La La Land','NEW_RELEASE');
    INSERT INTO PUBLIC.MOVIE (ID,CREATEDATE,CREATEUSER,ISACTIVE,UPDATEDATE,UPDATEUSER,DESCRIPTION,IMDBCODE,RELEASEDATE,TITLE,"TYPE") 
    VALUES (5,'2017-01-01 00:00:00.000',NULL,true,NULL,NULL,'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, the Dark Knight must come to terms with one of the greatest psychological tests of his ability to fight injustice.','tt0468569','2008-01-01 00:00:00.000','The Dark Knight','REGULAR');
    INSERT INTO PUBLIC.MOVIE (ID,CREATEDATE,CREATEUSER,ISACTIVE,UPDATEDATE,UPDATEUSER,DESCRIPTION,IMDBCODE,RELEASEDATE,TITLE,"TYPE") 
    VALUES (6,'2017-01-01 00:00:00.000',NULL,true,NULL,NULL,'A woman rebels against a tyrannical ruler in postapocalyptic Australia in search for her home-land with the help of a group of female prisoners, a psychotic worshipper, and a drifter named Max.','tt1392190','2015-01-01 00:00:00.000','Mad Max: Fury Road','REGULAR');
